"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!1q=&vzp52=017ijozwc0%lfu8g1k=tim^&mua#mp9cljq@*lp"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "gsheets"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
GSHEETS = {
  "type": "service_account",
  "project_id": "muanjia",
  "private_key_id": "81cde9689c0d301ebb5e1c0bb782e9afa522f601",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC8/1PGaYMJwViK\nQmj+zs+J5hsgJgnccYcgz+ytaz94oNYCV4actCBXnpkhVBlwIs8emc7IUgi07KoJ\nDOa5hGKmMSua++HOOqCq6YTk9/rcq5yoyeYJ0lr0X1yE3VVPIL/6nWLOgoS3Mu0b\nJ+e9gn/BtbAe5dv3lsA+hq0GnzEr8mUausxhpAX6DV/ytNPgU0OZOOOucuHHpQ5k\n5qiVbOMLZ2O71I6U8u6AIkhxIMXQdqTN+iiLzks5VMuxR+3KYL0heNtkqGIqhgQU\nzg+X38yZpFoW3tZLfxEc4rh81QLRDQ4p0MjECDfl1MkGaI1JTJr+aKmzqsHX26W/\n+iArl0yrAgMBAAECggEAJNaHl7bdKbub7GcBXBknbrOBOgTwCx29vvGIKk0rM/H1\nhMNWo5igbTOmmU5xHuBKCqbkHTuQIuO2SMlQ93wMVmRjIXRTEQVwZ5/YnWCQbw6s\nHGIuCmAMBnHH8MXLaP7zLIAc0C+0epjcilx+2Ptkt3cYew1GkL27fvR1KUNCLFRe\n91QUeS1N/xsuiauxqUeelmOFUg8iewFWaAhqikBshFVerBfwgYV3aycMKDw/klHp\nNQ+HoNVE2TP2yDFJEPokdP2seOgF8BT8uYBVUD4hSgUM8ss4mR2PLi3YiFm5QjHa\n2F1odMkYBHIxdNznlPrkyWakTlRs4B0FnkX0X+DX4QKBgQDl97m6KB92nlP//iwS\nU+cRvA4A7RrXYZAcWoOBDI5VxIUViwfKFZtkJVxGca5FYDE4uxIQxqpGBKfxg3uj\nndEKesDno+ANlQxZAg6OJX5VyDC+WM3+LlqfGgKVHlf5CiTuSeux/A2LMJXR1gm5\n7BmIXvYBBzQbsfDoMqRuowXnaQKBgQDSZFDglCV2nq0yfF2Pybi2fkCn4lJg2gA8\nNCz+MoPAhp2gNTyVLA2mzMu2lDirCKGJ6j/RODJLsxNhfZlH7Jtz+zUjHh9KR+Yx\nS82Ej8WESFOGGgJYzvr+yEvIVxu6dR5LMrzzdy8gCAzJHT6NGojaBaB6UfHqUNih\nBzsbRYcE8wKBgQDRbRd7u3xjxu5SjANQsY4WLX9HQqaWDKhz2c42oNuiqfRU2Sc/\n1wuLWSa+lFqTnXVV568dDf8VArp7DDV1nIw5ke7JRQkO9XSoPmJI+0YhEs2pGzCF\nUWt/xu0hJeAR0TYut6zoitU+tAFMdjKnWacq9OftqcS/j/4HR89NXjNLOQKBgQDP\nPHTV4ddNEltzwUC/o2lIiO/S7oFKWTGmG5a+BK/2ciLNbeLw5OXFiTCX9UQkZGoJ\n2S1nPj18hzXt77OOPyeYhLcAkmkr18qMgCg+DQf3lu5+xxvMsoRVdqH/Ap6TeU2P\nsLih8KIAoS1G5IF6p8ppRuWd1x29OklHxEGaSVAHtQKBgQDBYYMnKQQpZwuktdT9\nsvZJq0MuRoSgVa/miUZqpaDSQStrksX0/M2xbFFuAhjbwQQTpO8K4dX/GD0gz9TN\nQ2HeElNkmXSK0tNazTHc7UYjtm7K62i/5kIks0g/z0rrdxG54dTiGBJ2TsQEV87O\nPhX/KS69d61Fv13uheFyXSaAqA==\n-----END PRIVATE KEY-----\n",
  "client_email": "spy-241@muanjia.iam.gserviceaccount.com",
  "client_id": "116373356867446353378",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/spy-241%40muanjia.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
